### ISSUE TITLE
cannot read property 'then' of undefined on reboot.js

### ISSUE THREAD

**Issue by NoahGMD** [FamryAmri/Discord-Bot-GDPS#4]
`(node:21896) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'then' of undefined
    at /storage/emulated/0/download/(my-path)/botfiles/cmds/reboot.js:8:25
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
how can i fix this?

**Comment by FamryAmri** [comment]
In this version, reboot.js is properly useless..
just ignore the reboot.js and the shutdown.js or shutdown command is still working..
